### ISSUE TITLE
The first parameter to @version tag is ignored, and version field is blank in the output

### ISSUE THREAD

**Issue by susam** [phpDocumentor/phpDocumentor#1054]
I am using phpdoc 2.0.1 on Debian Testing version (Jessie).

```
$ phpdoc --version 2> /dev/null
phpDocumentor version 2.0.1
```

Here is a test script foo.php to reproduce the issue:

```
<?php
/**
 * Foo script
 *
 * This script contains a class called Foo.
 *
 * @author Humpty Dumpty
 * @copyright 2013 Humpty Dumpty
 * @license http://creativecommons.org/publicdomain/zero/1.0/ Public domain
 * @version 0.1
 */

/**
 * Foo class
 *
 * This class contains a method called foo.
 *
 * @author Humpty Dumpty
 * @copyright 2013 Humpty Dumpty
 * @license http://creativecommons.org/publicdomain/zero/1.0/ Public domain
 * @version 0.1
 */
class Foo
{
    /**
     * Prints foo
     *
     * @return void
     */
    public function foo()
    {
        echo "foo\n";
    }
}
?>
```

After executing `phpdoc -d . -t docs` to generate the
documentation, this is what I see:

![blank-version](https://f.cloud.github.com/assets/229488/1269242/1b92145a-2cf5-11e3-8c69-266380048adf.png)

You can see that the 'Version' field appears to be blank.

However if I change the `@version` tag from

```
@version 0.1
```

to

```
@version 0.1 Unstable
```

then I see the following output:

![unstable-version](https://f.cloud.github.com/assets/229488/1269244/2928576e-2cf5-11e3-9169-26362e668de7.png)

It looks like only the second parameter to `@version` tag is
displayed in the output. From the documentation at
http://www.phpdoc.org/docs/latest/for-users/phpdoc/tags/version.html
it looks like, `@version 0.1` should also work, i.e. the first
parameter to `@version` tag should also be displayed in the
output.

This issue occurs for `@since` tag too.

**Comment by TheCodePianist** [comment]
Are we going to see this? It seems like it is still not working correctly...

**Comment by jaapio** [comment]
@TheCodePianist can you confirm this issue is solved with the version that is currently available in master? I think it is solved.

**Comment by ve3** [comment]
I'm using phpDocumentor 2.9.0 but @version 1.0 is still not working.

**Comment by jaapio** [comment]
@ve3 can you tell me in which situation @version 1.0 doesn't work for you? Do you have a public example? Which template are you using?

**Comment by ve3** [comment]
@jaapio https://github.com/phpDocumentor/phpDocumentor2/issues/1843

**Comment by mvriel** [comment]
I doublechecked whether this issue still exists in the latest version using the default template and it seems to be fine now:
![image](https://user-images.githubusercontent.com/193704/206535640-e637bda6-a710-4cb6-b1f8-ea000833e63c.png)

As such, I am closing this issue as resolved
