### ISSUE TITLE
3.0.0-rc Fatal TWIG error, Failed to get magic properties ... is not a valid Fqsen

### ISSUE THREAD

**Issue by averageflow** [phpDocumentor/phpDocumentor#2355]
I really love phpDocumentor and am a big fan and have always used it. Now with PHP 7.4 and Laravel 7 project I can't get past this error. Documenting specific folders works fine, but this class is making the whole project error out, no documentation generated.

## Expected Behavior
I would expect the errors to be non fatal.

## Actual Behavior
No documentation is generated because of this error. The class in question is an abstract class. Documenting other folders of my project works fine.

## Steps to Reproduce the Problem

  1. Launch the phar to create the documentation

## Your environment

* Version used: 3.0.0-rc
* PHAR
* PHP 7.4.5
* macOS Catalina
* Laravel project

Stack trace:
```
✓ joe@Joseps-MBP workspace/docs_api > php phpDocumentor.phar run -d /Users/joe/workspace/site_api/domain -t /Users/joe/workspace/docs_api/docs/
phpDocumentor v3.0.0-rc

Parsing files
 209/209 [============================] 100%
Applying transformations (can take a while)
  5/16 [========>-------------------]  31%14:43:00 ERROR     [console] Error thrown while running command "run -d '/Users/joe/workspace/site_api/domain' -t '/Users/joe/workspace/docs_api/docs/'". Message: "An exception has been thrown during the rendering of a template ("Failed to get magic properties from "\Domain\Configurations\Models\ConfigurationModel": "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen.")." ["exception" => Twig\Error\RuntimeError^ { …},"command" => "run -d '/Users/joe/workspace/site_api/domain' -t '/Users/joe/workspace/docs_api/docs/'","message" => "An exception has been thrown during the rendering of a template ("Failed to get magic properties from "\Domain\Configurations\Models\ConfigurationModel": "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen.")."]
14:43:00 ERROR     [console] Error thrown while running command "run -d '/Users/joe/workspace/site_api/domain' -t '/Users/joe/workspace/docs_api/docs/'". Message: "An exception has been thrown during the rendering of a template ("Failed to get magic properties from "\Domain\Configurations\Models\ConfigurationModel": "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen.")." ["exception" => Twig\Error\RuntimeError^ { …},"command" => "run -d '/Users/joe/workspace/site_api/domain' -t '/Users/joe/workspace/docs_api/docs/'","message" => "An exception has been thrown during the rendering of a template ("Failed to get magic properties from "\Domain\Configurations\Models\ConfigurationModel": "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen.")."]

In class.html.twig line 66:

  An exception has been thrown during the rendering of a template ("Failed to get magic properties from "\Domain\Conf
  igurations\Models\ConfigurationModel": "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen."
  ).


In ClassDescriptor.php line 270:

  Failed to get magic properties from "\Domain\Configurations\Models\ConfigurationModel": "\Domain\Configurations\Mod
  els\ConfigurationModel::$" is not a valid Fqsen.


In Fqsen.php line 51:

  "\Domain\Configurations\Models\ConfigurationModel::$" is not a valid Fqsen.
```

The class in question:

```
<?php declare(strict_types=1);


namespace Domain\Configurations\Models;


use Domain\Attributes\Models\Attribute;
use Domain\Configurations\ConfigurationHelpers;
use Domain\Products\Models\Product;
use Domain\Stores\Models\Store;
use Domain\StoreUsers\Models\StoreUser;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Support\Collection;
use Infrastructure\Traits\HasUid;

/**
 * Class ConfigurationModel
 * @package Domain\Configurations\Models
 * @property array|mixed contents
 */
abstract class ConfigurationModel extends Model {
    use HasUid;
    use SoftDeletes;

    protected $dateFormat = 'U';
    protected $fillable = [
        CONTENTS,
        STORE_ID,
        USER_ID,
    ];

    protected $casts = [
        CONTENTS => 'array',
        'updated_at' => DATETIME,
        CREATED_AT => DATETIME,
    ];

    /**
     * Evaluate if the collection contains a specified configuration.
     * If it does then replace quantities, and if it does not then push to collection.
     * This function returns a modified version of the input collection.
     * @param array $properties
     * @param Collection $contents
     * @param bool $requiresIDTranslation
     * @return Collection
     */
    public static function replaceOrPushContents(array $properties, Collection $contents, bool $requiresIDTranslation = true): Collection {
        if ($requiresIDTranslation) {
            $properties = self::formatConfigurationContents($properties);
        }
        $existing = ConfigurationHelpers::doesItemExist($contents, $properties);
        if ($existing) {
            $contents = ConfigurationHelpers::replaceExistingItemsInConfiguration($contents, $properties);
        } else {
            $contents->push($properties);
        }
        return $contents;
    }

    /**
     * Translate from IDs to UUIDs to create a frontend friendly version.
     * @param array $properties
     * @return array
     */
    public static function formatConfigurationContents(array $properties): array {
        $properties[PRODUCT_ID]
            = (new Product)->findByUid($properties[PRODUCT_ID])->getAttribute(ID);

        $configString = json_encode($properties[CONFIGURATION]);
        $properties[CONFIGURATION] =
            ConfigurationHelpers::formattedConfiguration($configString, $properties[CONFIGURATION]);

        $accessoriesString = json_encode($properties[ACCESSORIES]);
        $properties[ACCESSORIES] =
            ConfigurationHelpers::formattedAccessories($accessoriesString, $properties[ACCESSORIES]);
        return $properties;
    }

    /**
     * Get model instances associated to the config entry.
     * @param array $properties
     * @return array
     */
    public static function processFromConfigToModel(array $properties): array {
        $productID = (new Product)->findByUid($properties[PRODUCT_ID])->getAttribute(ID);
        $configuration = [];
        if (array_key_exists(CONFIGURATION, $properties)) {
            $configuration = Attribute::whereIn(UID, $properties[CONFIGURATION])
                ->pluck(ID)
                ->sort()
                ->values()
                ->toArray();
        }
        return [
            PRODUCT_ID => $productID,
            CONFIGURATION => $configuration,
        ];
    }

    /**
     * Contents getter.
     * @return array
     */
    public function getContents(): array {
        return $this->getAttribute(CONTENTS)->toArray();
    }

    /**
     * Contents setter.
     * @param array $data
     * @return void
     */
    public function setContents(array $data): void {
        $this->setAttribute(CONTENTS, $data);
    }

    /**
     * Every subclass of Configuration Model should be able to retrieve the respective
     * cart/favourite for a given user in a given store.
     * @param int $userID
     * @param int $storeID
     * @return ConfigurationModel
     */
    abstract public function getModel(int $userID, int $storeID): ConfigurationModel;

    /**
     * Each configuration can only belong to one user.
     * @return BelongsTo
     */
    public function user(): BelongsTo {
        return $this->belongsTo(StoreUser::class);
    }

    /**
     * Each configuration can only belong to one store.
     * @return BelongsTo
     */
    public function store(): BelongsTo {
        return $this->belongsTo(Store::class);
    }

}
```

**Comment by jaapio** [comment]
I remember that I fixed an issue on this subject a few days ago. You could give the nightly build a try:
https://github.com/phpDocumentor/phpDocumentor/suites/665739262/artifacts/5921743

Please let me now if this solves the issue for you.

**Comment by averageflow** [comment]
Thanks for the quick reply @jaapio , but it still does not work. I get exactly the same issue.

**Comment by averageflow** [comment]
I launch it with `php phpDocumentor.phar run -d /Users/joe/workspace/site_api/domain -t /Users/joe/workspace/docs_api/docs/` and i still did not make a config file if that makes a difference

**Comment by nmch** [comment]
@averageflow 
 try this:
`@property array|mixed $contents`
