### ISSUE TITLE
Generating the class diagram failed

### ISSUE THREAD

**Issue by Xymph** [phpDocumentor/phpDocumentor#3735]
The class diagram SVG is not generated, only classes.html. This still worked correctly in v3.4.3.

## Expected behavior

A successfully generated class diagram.

## Actual behavior

Log excerpt with level 3 verbosity (which in this segment has no additional lines over level 1, btw):
```
[notice]   Writer RenderGuide  on 
[notice]   Writer Graph  on graphs/classes.svg
[error] Generating the class diagram failed
[error] Generating the class diagram failed
[notice] Finished transformation process
```
And classes.svg is not generated.

The current directory contains a new `ast.dump` file with type "Solitaire Image Recorder format".

## Steps to reproduce the problem

phpDocumentor.phar  -vvv --title=Wikimate -d . -i examples.php --sourcecode -t <path_to_my_private_site> -s graphs.enabled=true

## Your environment

* Version used: 3.5.0
* Install method: downloaded PHAR
* PHP version: 8.3
* Operating system and version: Ubuntu 22.04
* Link to your project: https://github.com/hamstar/Wikimate

**Comment by apohutenumera** [comment]
The output produced by phpDocumentor -vvvv

```
phpDocumentor v3.5.3

[notice] Starting stage: League\Pipeline\Pipeline
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Configure
[notice] Using the configuration file at the default location
[info] Logging to: /test_repo/.phpdoc/cache
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Configure in 12 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\TransformToPayload
[notice] Completed stage: phpDocumentor\Pipeline\Stage\TransformToPayload in 0 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\InitializeBuilderFromConfig
[notice] Completed stage: phpDocumentor\Pipeline\Stage\InitializeBuilderFromConfig in 0 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Cache\PurgeCachesWhenForced
[info] Checking whether to purge cache
[info] Purging cache
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Cache\PurgeCachesWhenForced in 3688 ms
[notice] Completed stage: League\Pipeline\Pipeline in 3701 ms
[notice] Starting stage: League\Pipeline\Pipeline
[notice] Starting stage: phpDocumentor\Pipeline\Stage\ParseApiDocumentationSets
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Parser\CollectFiles
[info] Collecting files from /test_repo/
[info] OK
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Parser\CollectFiles in 3564 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Cache\GarbageCollectCache
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Cache\GarbageCollectCache in 2 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Parser\ParseFiles
[notice] Parsing files
....
[info] Elapsed time to parse all files: 0.62s
[info] Peak memory usage: 44.95M
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Parser\ParseFiles in 621 ms
[notice] Completed stage: phpDocumentor\Pipeline\Stage\ParseApiDocumentationSets in 4188 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache in 0 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Parser\ParseGuides
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Parser\ParseGuides in 0 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Cache\StoreProjectDescriptorToCache
[notice] Storing cache ..
[info] OK
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Cache\StoreProjectDescriptorToCache in 342 ms
[notice] Completed stage: League\Pipeline\Pipeline in 4531 ms
[notice] Starting stage: League\Pipeline\Pipeline
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache
[info] Loading project from cache
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Cache\LoadProjectDescriptorFromCache in 163 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Compile
[notice] Starting stage: phpDocumentor\Compiler\Version\Pass\SetVersionPass
[notice] Completed stage: phpDocumentor\Compiler\Version\Pass\SetVersionPass in 0 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Compiler\DocumentationSetCompiler
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\ElementsIndexBuilder
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\ElementsIndexBuilder in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Linker\Linker
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Linker\Linker in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\PackageTreeBuilder
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\PackageTreeBuilder in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\MarkerFromTagsExtractor
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\MarkerFromTagsExtractor in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\NamespaceTreeBuilder
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\NamespaceTreeBuilder in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\ResolveInlineMarkers
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\ResolveInlineMarkers in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\UsedByBuilder
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\UsedByBuilder in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\VarTagModifier
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\VarTagModifier in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\FilterEmptyNamespaces
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\FilterEmptyNamespaces in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\RemoveSourcecode
[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\RemoveSourcecode in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\ApiDocumentation\Pass\Debug
[debug] In the Project are:
        10 files
         0 top-level namespaces
         0 unresolvable parent classes
         4 phpDocumentor\Descriptor\ConstantDescriptor elements
         2 phpDocumentor\Descriptor\ClassDescriptor elements
        19 phpDocumentor\Descriptor\MethodDescriptor elements
         4 phpDocumentor\Descriptor\PropertyDescriptor elements
         1 phpDocumentor\Descriptor\NamespaceDescriptor elements

[notice] Completed stage: phpDocumentor\Compiler\ApiDocumentation\Pass\Debug in 0 ms
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Compiler\DocumentationSetCompiler in 1 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Compiler\DocumentationSetCompiler
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Compiler\DocumentationSetCompiler in 0 ms
[notice] Starting stage: phpDocumentor\Compiler\Version\Pass\TableOfContentsBuilder
[notice] Completed stage: phpDocumentor\Compiler\Version\Pass\TableOfContentsBuilder in 1 ms
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Compile in 3 ms
[notice] Starting stage: phpDocumentor\Pipeline\Stage\Transform
[info]
Applying 22 transformations
[notice]   Writer twig  on index.html
[notice]   Writer twig  using query "$.files" on
[notice]   Writer sourcecode  using query "$.files" on files/{{path}}.txt
[notice]   Writer twig  using query "$.indexes.namespaces" on
[notice]   Writer twig  using query "$.indexes.packages" on
[notice]   Writer twig  using query "$.indexes.classes" on
[notice]   Writer twig  using query "$.indexes.enums" on
[notice]   Writer twig  using query "$.indexes.interfaces" on
[notice]   Writer twig  using query "$.indexes.traits" on
[notice]   Writer twig  on js/template.js
[notice]   Writer twig  on js/search.js
[notice]   Writer twig  on js/searchIndex.js
[notice]   Writer twig  on graphs/classes.html
[notice]   Writer twig  on reports/errors.html
[notice]   Writer twig  on reports/deprecated.html
[notice]   Writer twig  on reports/markers.html
[notice]   Writer twig  on indices/files.html
[notice]   Writer twig  on css/base.css
[notice]   Writer twig  on css/normalize.css
[notice]   Writer twig  on css/template.css
[notice]   Writer RenderGuide  on
[notice]   Writer Graph  on graphs/classes.svg
[error] Generating the class diagram failed
[error] Generating the class diagram failed
[notice] Finished transformation process
[notice] Completed stage: phpDocumentor\Pipeline\Stage\Transform in 609 ms
[notice] Completed stage: League\Pipeline\Pipeline in 775 ms
```

**Comment by Xymph** [comment]
It's nice to have a v3.6 release, but I'm afraid that it didn't resolve this issue. I removed the .phpdoc dir from my source tree, and generate the output to a new tree on my website, but the `[error] Generating the class diagram failed` persists.
The /graphs/ directory contains file classes.html, but not classes.svg.

@jaapio  Is there something I could try to help you analyze the bug? Am I missing a tool to generate .svg files?

**Comment by jaapio** [comment]
We are using plantuml which is a java application, so you need to have java installed. Plantuml itself is shipped in the phar.
Plantuml uses graphiz to render diagrams, so that needs to be installed.

I now realize that we need to improve the debug options on this. As the output of the rendering is completely hidden. So you are in the dark now. 

Let me fix that first, so we can get some more data.

**Comment by jaapio** [comment]
I started testing this more and discovered there are a lot of improvements needed and possible, so I'm currently implementing those and adding extra documentation about the diagram generation. 

It will take some time, but it's good that I'm doing this.

**Comment by Xymph** [comment]
Glad to hear it. I did have java, plantuml and graph**v**iz installed indeed, so at least my problem wasn't from lack of meeting the requirements (it did work thru v3.4.3 after all).

**Comment by molekola-io** [comment]
Hi all, I am facing the same issue:

I installed phpDocumentor.phar and I need to integrate mermaid diagrams, but I don't understand how to do that.

Here you can see the setup:
- phpDocumentor v. 3.6.0 (phar)
- php v.8.3.16
- java v. 23.0.2 (I can change if needed)

The file is stored outside the project directory and this is the directory tree:

- projects
  - phpDocumentor.phar
  - myproject
    - phpdoc.dist.xml
    - src/

The phpdoc conf file contains:
```xml
<?xml version="1.0" encoding="UTF-8" ?>
<phpdocumentor configVersion="3" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns="https://www.phpdoc.org"
               xsi:noNamespaceSchemaLocation="https://raw.githubusercontent.com/phpDocumentor/phpDocumentor/master/data/xsd/phpdoc.xsd"
               xsi:schemaLocation="https://www.phpdoc.org ">
    <title>Eolia Web API</title>
    <paths>
        <output>phpdoc/out/api</output>
        <cache>phpdoc/cache</cache>
    </paths>
    <version number="3.0.0">
        <api>
            <source dsn=".">
                <path>src</path>
            </source>
        </api>
    </version>
    <settings>
        <setting name="markdown.enabled">true</setting>
        <graphs>
                <name>enabled</name>
                <value>true</value>
        </graphs>
    </settings>
    <templates>
        <template name="default"/>
    </templates>
</phpdocumentor>
```

I run phpdoc in this way:
```
../phpDocumentor.phar --setting=graphs.enabled=true
```

the `--setting=graphs.enabled=true` switch in cli is because I don't understand how to configure this in the settings section:

```xml
    <settings>
       <!-- ... -->
        <graphs>
                <name>enabled</name>
                <value>true</value>
        </graphs>
    </settings>
```

Is there a guide I can follow to do the correct setup or is it better to wait for the next release?

Unfortunately I can use phar or docker setup only because of the nature of the project.

**Comment by molekola-io** [comment]
I found the right way to enable / disable settings in config xml:

```xml
<phpdocumentor>
    <!--
        Settings are placed as direct child of the root node.
       -->
    <setting name="markdown.enabled" value="true"/>
    <setting name="graphs.enabled" value="true"/>
    <setting name="template.color" value="blue"/>
</phpdocumentor>
```

I found it here: [Configuration](https://docs.phpdoc.org/guide/references/configuration.html)

**Comment by jaapio** [comment]
I just released phpDoc 3.7 which allows you to configure plantuml to avoid issues like this. The functionality has been documented: https://docs.phpdoc.org/guide/guides/generate-diagrams.html#generate-diagrams

**Comment by Xymph** [comment]
Hate to be the bearer of bad news, but 3.7.0 still doesn't produce a class image with the phar file, and no clear error message to explain why not. I did:

```
$ export PHPDOC_PLANTUML_BIN=/usr/bin/plantuml
$ rm -rf .phpdoc/
$ phpdoc run -vvv --title=Wikimate -d . -i vendor/ --sourcecode -t /var/www/<...path...>/ -s graphs.enabled=true
phpDocumentor 3.7.0
[...]
   Writer RenderGuide  on 
   Execute transformation using writer "RenderGuide"
   Writer Graph  on graphs/classes.svg
   Execute transformation using writer "Graph"
 Generating the class diagram failed: {error}
 Finished transformation process
 Completed stage: phpDocumentor\Pipeline\Stage\Transform in 439 ms
 Completed stage: phpDocumentor\Pipeline\Pipeline in 449 ms

All done in 1 seconds!
```
A `ast.dump` file of 722998 bytes is left in the currect directory, seems to be Solitaire Image Recorder format for which I didn't look for a viewer.
Using PlantUML v1.2020.02 which is current on 22.04 LTS.

How can we debug this further?

**Comment by jaapio** [comment]
I'm sorry to hear that I did break the error output. With the new 3.7.1 release this has been fixed. You should see the error:

`Generating the class diagram failed: {error}`   will become:

`Generating the class diagram failed: /opt/project/vendor/jawira/plantuml/bin/plantuml: line 11: exec: java: not found` 

Let me know when you got more information on this so we can find the cause of the error.

**Comment by Xymph** [comment]
3.7.1 -vvv generates this output excerpt:

```
   Writer RenderGuide {querty} on 
   Execute transformation using writer "RenderGuide"
   Writer Graph {querty} on graphs/classes.svg
   Execute transformation using writer "Graph"
 Generating the class diagram failed: Unable to launch a new process.
 Finished transformation process
```
Hope it helps.

**Comment by jaapio** [comment]
Looks like php cannot spawn a child process for some reason. Does it work if you try to run plantuml manually?

**Comment by Xymph** [comment]
Yes, running 'plantuml' without options gives me a window with a File menu and an About entry that shows:

```
Loaded from jar:file:/usr/share/plantuml/plantuml.jar!/  
The environment variable GRAPHVIZ_DOT has not been set 
Dot executable is /usr/bin/dot 
Dot version: dot - graphviz version 2.43.0 (0) 
Installation seems OK. File generation OK  

Java Runtime: OpenJDK Runtime Environment 
JVM: OpenJDK 64-Bit Server VM 
Java Version: 11.0.26+4-post-Ubuntu-1ubuntu122.04 
Operating System: Linux 
Default Encoding: UTF-8 
Language: en 
[...etc...]
```

**Comment by jaapio** [comment]
This seems to be related to these lines: https://github.com/symfony/process/blob/5.4/Process.php#L352-L353

Which means that for some reason your system doesn't allow phpDocumentor to start a new process. The actual cause seems to be hidden. 

What you could try to debug this is clone this repository. And do a composer install. Find the process class and remove @ from the lines. 

I did send the link to the previous version of this file so the line numbers might be off. If you now run phpdoc again you might get an error that explains better what is wrong. 

---
I'm typing this on my phone, so I cannot debug this myself right now. But I wasn't able to reproduce this particular error today.

**Comment by Xymph** [comment]
After cloning/composer update, I get the following output:

```
$ ~/phpDocumentor/bin/phpdoc run -vvv --title=Wikimate -d . -i vendor/ --sourcecode -t /var/www/htdocs/<path>/ -s graphs.enabled=true
phpDocumentor 3.4.2-dev-master+d8afc82
[...]
   Writer Graph {querty} on graphs/classes.svg
   Execute transformation using writer "Graph"
 Generating the class diagram failed: Error line 15 in file: /tmp/phpdocumentor/pu_qhK9Gk
Some diagram description contains errors
 Finished transformation process
```
That temp file has the following contents:
```
@startuml
   skinparam ArrowColor #516f42
   skinparam activityBorderColor #516f42
   skinparam activityBackgroundColor #ffffff
   skinparam activityDiamondBorderColor #516f42
   skinparam activityDiamondBackgroundColor #ffffff
   skinparam shadowing false

skinparam shadowing false
skinparam linetype ortho
hide empty members
left to right direction
set namespaceSeparator \\

namespace  {
     class "Wikimate" as Wikimate__class    {
    }
}
class "RuntimeException" as RuntimeException__class << external >>{
}
namespace  {
     class "WikimateException" as WikimateException__class   extends \\RuntimeException_
_class  {
    }
}
namespace  {
     class "WikiPage" as WikiPage__class    {
    }
}
namespace  {
     class "WikiFile" as WikiFile__class    {
    }
}

@enduml
```
Line 15 is the first "namespace" line.

Is "v3.4.2-dev-master+d8afc82" correct? Odd that it doesn't show 3.7.1.

**Comment by jaapio** [comment]
Ok, it looks like the generated uml is in correct as your classes are not namespaced. 

This needs another patch. Thanks for debugging. I will have a look what is happening.

**Comment by haykonus** [comment]
A very nice tool. Creating diagrams would be the highlight. During the generating of diagrams I ran with docker on ubuntu 24.04 with phpDocumentor 3.4.2-v3.8.0+d238c57 in the same issue.

`@startuml
   skinparam ArrowColor #516f42
   skinparam activityBorderColor #516f42
   skinparam activityBackgroundColor #ffffff
   skinparam activityDiamondBorderColor #516f42
   skinparam activityDiamondBackgroundColor #ffffff
   skinparam shadowing false

skinparam shadowing false
skinparam linetype ortho
hide empty members
left to right direction
set namespaceSeparator \\

namespace  {
     class "Fruit" as Fruit__class    {
    }
}

@enduml
`
Is there a solution on the horizon ... ?

**Comment by jaapio** [comment]
No there is no progress on this item. Pr would be appreciated. I do not have time to dig into this

**Comment by franck-paul** [comment]
Ok, but as I do not know anything about Java (and the according documentation page seems to be broken, https://docs.phpdoc.org/graphs/classes.html) I will let this for another with better skills in this matter.
